### ISSUE TITLE
Is there a timeframe for the documentation?

### ISSUE THREAD

**Issue by Michael-Brooks** [nsbucky/echosignv3#1]
Hello,

I would really like to use this for my new project, but I'm having trouble with starting out. Is there any documentation which you are planning to add? If so, when will you be adding it?

I just need the bare basics on starting up, then I can just check out the tests and work from there.

Here is my code so far...

```
   $transport = new GuzzleTransport();

    $widget = new Widgets('1234', $transport);

    $fileInfo = new WidgetFileInfo();
    $fileInfo->setLibraryDocumentId('test');

    $docCreate = new WidgetCreationInfo('test', 'SENDER_SIGNATURE_NOT_REQUIRED', $fileInfo);
    $widget->create($docCreate);
```

Where it says '1234', that is where I placed my created Integration key (not sure if this is what should be there). If it isn't, then I need to know what should be placed there and how I get it.

What I want to do as an overall outcome is send a pdf over to Echo Sign's widget, then email a user the link to that widget so they can sign it. Any help would be appreciated.

**Comment by nsbucky** [comment]
Ill be working on documentation soon. I created this library out of a need for a project at work, and am actively developing it as needed. There is some documentation that is automatically generated in the apigen folder, but you're right, it would be helpful to have some more start up docs. The tests are a good way to get an idea of what to do.

The '1234' is the integration key. Adobe for the version 3 of the REST API uses oAuth to generate those tokens. There are a few libraries out there like: https://github.com/Lusitanian/PHPoAuthLib for consuming oAuth services and generating the authentication tokens. This is different from previous versions of their REST API.

Right now my library is a tad verbose, I'll be working on ways to wrap up some of the class calls to make it easier to accomplish common tasks. Or hey you could ;)

According to their docs and using the library: https://secure.echosign.com/public/docs/restapi/v3 this is how you would accomplish that:

First you will need to upload a document using the transientDocument endpoint:

```
$filename = '/path/to/your/local/file.doc|pdf|etc';
$transport = new GuzzleTransport();
$token = 'your-authentication-token';
$td =  new TransientDocuments( $token, $transport );

try {
    $transDoc = $transientDocument->create( $filename );
} catch( \Exception $e ) {
    echo $e->getMessage();
    return;
}
```

According to Adobe, you should also be able to specify a url you host for use as a library document. Take a look at the URLFileInfo for more information.

Then you will need to create your library document to use with the widget:

```
$libraryDocuments = new LibraryDocuments( $token, $transport );
$fileInfo = new FileInfo();
$fileInfo->setTransientDocumentId( $td->getTransientDocumentId() );
$creationInfo = new LibraryDocumentCreationInfo( $document->name, 'DOCUMENT', $fileInfo, 'USER' );
$docCreate    = new LibraryCreationInfo( $creationInfo, new InteractiveOptions() );
// if you specify userId, then the library document will be created for that 
// user, otherwise its available for all users
$userId       = '123Acd.....'; 

try {
    $result = $libraryDocuments->create( $docCreate, $userId );
} catch( \Exception $e ) {
    echo $e->getMessage();
    return;
}
```

so now you have a library document id: 

```
$result->getLibraryDocumentId();
```

This can be used in your widget calls:

```
$widget = new Widgets($token, $transport);
$fileInfo = new WidgetFileInfo();
$fileInfo->setLibraryDocumentId( $result->getLibraryDocumentId() );
$docCreate = new WidgetCreationInfo('name_of_widget', 'SENDER_SIGNATURE_NOT_REQUIRED', $fileInfo);
try{
    $widgetCreated = $widget->create($docCreate);
} catch(\Exception $e) {
    echo $e->getMessage();
    return;
} 

$url = $widgetCreated->getUrl(); // url you want to email out.
```

**Comment by nsbucky** [comment]
I added some new creators to try and make this easier.

**Comment by Michael-Brooks** [comment]
That will help when looking for somewhere to start. :) Thanks for your help, it's working nicely now. :D
