### ISSUE TITLE
composer update

### ISSUE THREAD

**Issue by m0h1tx** [nsbucky/echosignv3#2]
hey nsbucky
                     i am facing folowing error when i tried to update...

> C:\ProgramData\ComposerSetup\bin\composer.bat update
> You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package nsbucky/echosignv3 No version set (parsed as 1.0.0) could not be found.
  Problem 2
    - Installation request for mockery/mockery dev-master@dev -> satisfiable by mockery/mockery[dev-master].
    - mockery/mockery dev-master requires hamcrest/hamcrest-php ^2.0@dev -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

**Comment by nsbucky** [comment]
Try using this in your composer require:
`"require": {
        "nsbucky/echosignv3": "^1.1"
    }`
